name: welcome
on: workflow_dispatch 
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: greet
        run: echo "welcome to ubtuntu"
      - name: server operating
        run: cat /etc/os-release
      - name: Memory and storage
        run: |
          free -m
          free -h
          df -h
          lscpu
